name: Hello World

on:
  push:
  pull_request:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, World!"

      - name: Show event name
        run: echo "This event is: ${{ github.event_name }}"

      - name: List repo files
        run: ls -la
